#!/bin/bash
# Grid Engine options (lines prefixed with #$)
# job name: -N
# use the current working directory: -cwd
# number of cores -pe sharedmem
# runtime limit: -l h_rt
# memory limit: -l h_vmem
#$ -N tumourHamedscMouse
#$ -cwd
#$ -pe sharedmem 8
#$ -l h_rt=48:00:00
#$ -l h_vmem=8G
#$ -e error1.txt
#$ -o output1.txt

## Initialising the environment modules
. /etc/profile.d/modules.sh
# /exports/applications/apps/user-scripts/

# Loading modules*
module load igmm/apps/nextflow/24.04.4
module load singularity


#Complete paths to genome files
GTF_PATH=/gpfs/igmmfs01/eddie/BioinformaticsResources/igenomes/Mus_musculus/Ensembl/GRCm39/Annotation/Genes/genes.gtf
FASTA_PATH=/gpfs/igmmfs01/eddie/BioinformaticsResources/igenomes/Mus_musculus/Ensembl/GRCm39/Sequence/WholeGenomeFasta/genome.fa
OUTPUT_DIR=/exports/eddie/scratch/ngiannak/Data/singleEndRNAseq/output
SAMPLESHEET=/exports/eddie/scratch/ngiannak/Data/singleEndRNAseq/samplesheet.csv


nextflow run nf-core/rnaseq \
--input=/exports/eddie/scratch/ngiannak/Data/singleEndRNAseq/samplesheet.csv \
--outdir=/exports/eddie/scratch/ngiannak/Data/singleEndRNAseq/output \
--gtf=/gpfs/igmmfs01/eddie/BioinformaticsResources/igenomes/Mus_musculus/Ensembl/GRCm39/Annotation/Genes/genes.gtf \
--fasta=/gpfs/igmmfs01/eddie/BioinformaticsResources/igenomes/Mus_musculus/Ensembl/GRCm39/Sequence/WholeGenomeFasta/genome.fa \
-profile eddie
